mongodb:
  uri: "localhost:27017"
  username: "username"
  password: "password"
  data_base: "m3u"

http:
  server_port: ":8080"
  read_timeout: 20s
  write_timeout: 20s
  max_header_megabytes: 1

telegram:
  telegram_token: ""
  chat_id: ""